
services:
  db:
    image: postgres:16-alpine
    container_name: infra-db-1
    environment:
      POSTGRES_DB: rosterdb
      POSTGRES_USER: roster
      POSTGRES_PASSWORD: roster
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roster -d rosterdb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    image: infra-backend:latest
    container_name: infra-backend-1
    environment:
      DATABASE_URL: postgresql+psycopg2://roster:roster@db:5432/rosterdb
      # Optional: make Uvicorn verbose
      LOG_LEVEL: info
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: build
    image: infra-frontend:latest
    container_name: infra-frontend-1
    # Dev: run Vite server inside this container for quick iteration
    command: ["sh","-lc","npm ci --no-audit --no-fund && npm run dev -- --host 0.0.0.0"]
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: infra-nginx-1
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

volumes:
  pgdata: {}
