services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: roster
      POSTGRES_PASSWORD: roster
      POSTGRES_DB: rosterdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roster -d rosterdb"]
      interval: 2s
      timeout: 2s
      retries: 15

  backend:
    build:
      context: ../backend          # ← from infra/ to project backend/
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env          # ← from infra/ to infra/env/backend.env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]

  frontend:
    build:
      context: ../frontend         # ← from infra/ to project frontend/
      dockerfile: Dockerfile
    # If using nginx proxy, set the API base to /api (see nginx service below)
    environment:
      - VITE_API_BASE=/api
    depends_on:
      - backend
    ports: ["5173:5173"]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf: # ← from infra/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  pgdata:
