services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: roster
      POSTGRES_PASSWORD: roster
      POSTGRES_DB: rosterdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    depends_on:
      - db
    ports: ["8000:8000"]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports: ["5173:5173"]
    depends_on:
      - backend

volumes:
  pgdata:
